package eqi 

var Pairs = []EquivalentPair{
	{
		VariantName: "CJK RADICAL CLIFF",
		Variant: "⺁",
		Unified: "厂",
	},
	{
		VariantName: "CJK RADICAL SECOND ONE",
		Variant: "⺂",
		Unified: "乛",
	},
	{
		VariantName: "CJK RADICAL SECOND TWO",
		Variant: "⺃",
		Unified: "乚",
	},
	{
		VariantName: "CJK RADICAL SECOND THREE",
		Variant: "⺄",
		Unified: "乙",
	},
	{
		VariantName: "CJK RADICAL PERSON",
		Variant: "⺅",
		Unified: "亻",
	},
	{
		VariantName: "CJK RADICAL BOX",
		Variant: "⺆",
		Unified: "冂",
	},
	{
		VariantName: "CJK RADICAL TABLE",
		Variant: "⺇",
		Unified: "𠘨",
	},
	{
		VariantName: "CJK RADICAL KNIFE ONE",
		Variant: "⺈",
		Unified: "刀",
	},
	{
		VariantName: "CJK RADICAL KNIFE TWO",
		Variant: "⺉",
		Unified: "刂",
	},
	{
		VariantName: "CJK RADICAL DIVINATION",
		Variant: "⺊",
		Unified: "卜",
	},
	{
		VariantName: "CJK RADICAL SEAL",
		Variant: "⺋",
		Unified: "㔾",
	},
	{
		VariantName: "[2] CJK RADICAL SMALL ONE..CJK RADICAL SMALL TWO",
		Variant: "⺌",
		Unified: "小",
	},
	{
		VariantName: "[2] CJK RADICAL SMALL ONE..CJK RADICAL SMALL TWO",
		Variant: "⺍",
		Unified: "小",
	},
	{
		VariantName: "CJK RADICAL LAME ONE",
		Variant: "⺎",
		Unified: "兀",
	},
	{
		VariantName: "CJK RADICAL LAME TWO",
		Variant: "⺏",
		Unified: "尣",
	},
	{
		VariantName: "CJK RADICAL LAME THREE",
		Variant: "⺐",
		Unified: "尢",
	},
	{
		VariantName: "CJK RADICAL LAME FOUR",
		Variant: "⺑",
		Unified: "𡯂",
	},
	{
		VariantName: "CJK RADICAL SNAKE",
		Variant: "⺒",
		Unified: "巳",
	},
	{
		VariantName: "CJK RADICAL THREAD",
		Variant: "⺓",
		Unified: "幺",
	},
	{
		VariantName: "CJK RADICAL SNOUT ONE",
		Variant: "⺔",
		Unified: "彑",
	},
	{
		VariantName: "CJK RADICAL SNOUT TWO",
		Variant: "⺕",
		Unified: "彐",
	},
	{
		VariantName: "CJK RADICAL HEART ONE",
		Variant: "⺖",
		Unified: "忄",
	},
	{
		VariantName: "CJK RADICAL HEART TWO",
		Variant: "⺗",
		Unified: "心",
	},
	{
		VariantName: "CJK RADICAL HAND",
		Variant: "⺘",
		Unified: "扌",
	},
	{
		VariantName: "CJK RADICAL RAP",
		Variant: "⺙",
		Unified: "攵",
	},
	{
		VariantName: "CJK RADICAL CHOKE",
		Variant: "⺛",
		Unified: "旡",
	},
	{
		VariantName: "CJK RADICAL SUN",
		Variant: "⺜",
		Unified: "日",
	},
	{
		VariantName: "CJK RADICAL MOON",
		Variant: "⺝",
		Unified: "月",
	},
	{
		VariantName: "CJK RADICAL DEATH",
		Variant: "⺞",
		Unified: "歺",
	},
	{
		VariantName: "CJK RADICAL MOTHER",
		Variant: "⺟",
		Unified: "母",
	},
	{
		VariantName: "CJK RADICAL CIVILIAN",
		Variant: "⺠",
		Unified: "民",
	},
	{
		VariantName: "CJK RADICAL WATER ONE",
		Variant: "⺡",
		Unified: "氵",
	},
	{
		VariantName: "CJK RADICAL WATER TWO",
		Variant: "⺢",
		Unified: "氺",
	},
	{
		VariantName: "CJK RADICAL FIRE",
		Variant: "⺣",
		Unified: "灬",
	},
	{
		VariantName: "[2] CJK RADICAL PAW ONE..CJK RADICAL PAW TWO",
		Variant: "⺤",
		Unified: "爫",
	},
	{
		VariantName: "[2] CJK RADICAL PAW ONE..CJK RADICAL PAW TWO",
		Variant: "⺥",
		Unified: "爫",
	},
	{
		VariantName: "CJK RADICAL SIMPLIFIED HALF TREE TRUNK",
		Variant: "⺦",
		Unified: "丬",
	},
	{
		VariantName: "CJK RADICAL COW",
		Variant: "⺧",
		Unified: "牛",
	},
	{
		VariantName: "CJK RADICAL DOG",
		Variant: "⺨",
		Unified: "犭",
	},
	{
		VariantName: "CJK RADICAL JADE",
		Variant: "⺩",
		Unified: "王",
	},
	{
		VariantName: "CJK RADICAL BOLT OF CLOTH",
		Variant: "⺪",
		Unified: "𤴔",
	},
	{
		VariantName: "CJK RADICAL EYE",
		Variant: "⺫",
		Unified: "目",
	},
	{
		VariantName: "CJK RADICAL SPIRIT ONE",
		Variant: "⺬",
		Unified: "示",
	},
	{
		VariantName: "CJK RADICAL SPIRIT TWO",
		Variant: "⺭",
		Unified: "礻",
	},
	{
		VariantName: "CJK RADICAL BAMBOO",
		Variant: "⺮",
		Unified: "𥫗",
	},
	{
		VariantName: "CJK RADICAL SILK",
		Variant: "⺯",
		Unified: "糹",
	},
	{
		VariantName: "CJK RADICAL C-SIMPLIFIED SILK",
		Variant: "⺰",
		Unified: "纟",
	},
	{
		VariantName: "CJK RADICAL NET ONE",
		Variant: "⺱",
		Unified: "罓",
	},
	{
		VariantName: "CJK RADICAL NET TWO",
		Variant: "⺲",
		Unified: "罒",
	},
	{
		VariantName: "CJK RADICAL NET THREE",
		Variant: "⺳",
		Unified: "㓁",
	},
	{
		VariantName: "CJK RADICAL NET FOUR",
		Variant: "⺴",
		Unified: "冗",
	},
	{
		VariantName: "CJK RADICAL MESH",
		Variant: "⺵",
		Unified: "𦉫",
	},
	{
		VariantName: "CJK RADICAL SHEEP",
		Variant: "⺶",
		Unified: "羊",
	},
	{
		VariantName: "CJK RADICAL RAM",
		Variant: "⺷",
		Unified: "𦍌",
	},
	{
		VariantName: "CJK RADICAL EWE",
		Variant: "⺸",
		Unified: "𦍋",
	},
	{
		VariantName: "CJK RADICAL OLD",
		Variant: "⺹",
		Unified: "耂",
	},
	{
		VariantName: "CJK RADICAL BRUSH ONE",
		Variant: "⺺",
		Unified: "肀",
	},
	{
		VariantName: "CJK RADICAL BRUSH TWO",
		Variant: "⺻",
		Unified: "聿",
	},
	{
		VariantName: "CJK RADICAL MEAT",
		Variant: "⺼",
		Unified: "肉",
	},
	{
		VariantName: "CJK RADICAL MORTAR",
		Variant: "⺽",
		Unified: "𦥑",
	},
	{
		VariantName: "[3] CJK RADICAL GRASS ONE..CJK RADICAL GRASS THREE",
		Variant: "⺾",
		Unified: "艹",
	},
	{
		VariantName: "[3] CJK RADICAL GRASS ONE..CJK RADICAL GRASS THREE",
		Variant: "⺿",
		Unified: "艹",
	},
	{
		VariantName: "[3] CJK RADICAL GRASS ONE..CJK RADICAL GRASS THREE",
		Variant: "⻀",
		Unified: "艹",
	},
	{
		VariantName: "CJK RADICAL TIGER",
		Variant: "⻁",
		Unified: "虎",
	},
	{
		VariantName: "CJK RADICAL CLOTHES",
		Variant: "⻂",
		Unified: "衤",
	},
	{
		VariantName: "CJK RADICAL WEST ONE",
		Variant: "⻃",
		Unified: "覀",
	},
	{
		VariantName: "CJK RADICAL WEST TWO",
		Variant: "⻄",
		Unified: "西",
	},
	{
		VariantName: "CJK RADICAL C-SIMPLIFIED SEE",
		Variant: "⻅",
		Unified: "见",
	},
	{
		VariantName: "CJK RADICAL SIMPLIFIED HORN",
		Variant: "⻆",
		Unified: "角",
	},
	{
		VariantName: "CJK RADICAL HORN",
		Variant: "⻇",
		Unified: "𧢲",
	},
	{
		VariantName: "CJK RADICAL C-SIMPLIFIED SPEECH",
		Variant: "⻈",
		Unified: "讠",
	},
	{
		VariantName: "CJK RADICAL C-SIMPLIFIED SHELL",
		Variant: "⻉",
		Unified: "贝",
	},
	{
		VariantName: "CJK RADICAL FOOT",
		Variant: "⻊",
		Unified: "𧾷",
	},
	{
		VariantName: "CJK RADICAL C-SIMPLIFIED CART",
		Variant: "⻋",
		Unified: "车",
	},
	{
		VariantName: "[3] CJK RADICAL SIMPLIFIED WALK..CJK RADICAL WALK TWO",
		Variant: "⻌",
		Unified: "辶",
	},
	{
		VariantName: "[3] CJK RADICAL SIMPLIFIED WALK..CJK RADICAL WALK TWO",
		Variant: "⻍",
		Unified: "辶",
	},
	{
		VariantName: "[3] CJK RADICAL SIMPLIFIED WALK..CJK RADICAL WALK TWO",
		Variant: "⻎",
		Unified: "辶",
	},
	{
		VariantName: "CJK RADICAL CITY",
		Variant: "⻏",
		Unified: "邑",
	},
	{
		VariantName: "CJK RADICAL C-SIMPLIFIED GOLD",
		Variant: "⻐",
		Unified: "钅",
	},
	{
		VariantName: "CJK RADICAL LONG ONE",
		Variant: "⻑",
		Unified: "長",
	},
	{
		VariantName: "CJK RADICAL LONG TWO",
		Variant: "⻒",
		Unified: "镸",
	},
	{
		VariantName: "CJK RADICAL C-SIMPLIFIED LONG",
		Variant: "⻓",
		Unified: "长",
	},
	{
		VariantName: "CJK RADICAL C-SIMPLIFIED GATE",
		Variant: "⻔",
		Unified: "门",
	},
	{
		VariantName: "CJK RADICAL MOUND ONE",
		Variant: "⻕",
		Unified: "𨸏",
	},
	{
		VariantName: "CJK RADICAL MOUND TWO",
		Variant: "⻖",
		Unified: "阝",
	},
	{
		VariantName: "CJK RADICAL RAIN",
		Variant: "⻗",
		Unified: "雨",
	},
	{
		VariantName: "CJK RADICAL BLUE",
		Variant: "⻘",
		Unified: "青",
	},
	{
		VariantName: "CJK RADICAL C-SIMPLIFIED TANNED LEATHER",
		Variant: "⻙",
		Unified: "韦",
	},
	{
		VariantName: "CJK RADICAL C-SIMPLIFIED LEAF",
		Variant: "⻚",
		Unified: "页",
	},
	{
		VariantName: "CJK RADICAL C-SIMPLIFIED WIND",
		Variant: "⻛",
		Unified: "风",
	},
	{
		VariantName: "CJK RADICAL C-SIMPLIFIED FLY",
		Variant: "⻜",
		Unified: "飞",
	},
	{
		VariantName: "CJK RADICAL EAT ONE",
		Variant: "⻝",
		Unified: "食",
	},
	{
		VariantName: "CJK RADICAL EAT TWO",
		Variant: "⻞",
		Unified: "𩙿",
	},
	{
		VariantName: "CJK RADICAL EAT THREE",
		Variant: "⻟",
		Unified: "飠",
	},
	{
		VariantName: "CJK RADICAL C-SIMPLIFIED EAT",
		Variant: "⻠",
		Unified: "饣",
	},
	{
		VariantName: "CJK RADICAL HEAD",
		Variant: "⻡",
		Unified: "𩠐",
	},
	{
		VariantName: "CJK RADICAL C-SIMPLIFIED HORSE",
		Variant: "⻢",
		Unified: "马",
	},
	{
		VariantName: "CJK RADICAL BONE",
		Variant: "⻣",
		Unified: "骨",
	},
	{
		VariantName: "CJK RADICAL GHOST",
		Variant: "⻤",
		Unified: "鬼",
	},
	{
		VariantName: "CJK RADICAL C-SIMPLIFIED FISH",
		Variant: "⻥",
		Unified: "鱼",
	},
	{
		VariantName: "CJK RADICAL C-SIMPLIFIED BIRD",
		Variant: "⻦",
		Unified: "鸟",
	},
	{
		VariantName: "CJK RADICAL C-SIMPLIFIED SALT",
		Variant: "⻧",
		Unified: "卤",
	},
	{
		VariantName: "CJK RADICAL SIMPLIFIED WHEAT",
		Variant: "⻨",
		Unified: "麦",
	},
	{
		VariantName: "CJK RADICAL SIMPLIFIED YELLOW",
		Variant: "⻩",
		Unified: "黄",
	},
	{
		VariantName: "CJK RADICAL C-SIMPLIFIED FROG",
		Variant: "⻪",
		Unified: "黾",
	},
	{
		VariantName: "CJK RADICAL J-SIMPLIFIED EVEN",
		Variant: "⻫",
		Unified: "斉",
	},
	{
		VariantName: "CJK RADICAL C-SIMPLIFIED EVEN",
		Variant: "⻬",
		Unified: "齐",
	},
	{
		VariantName: "CJK RADICAL J-SIMPLIFIED TOOTH",
		Variant: "⻭",
		Unified: "歯",
	},
	{
		VariantName: "CJK RADICAL C-SIMPLIFIED TOOTH",
		Variant: "⻮",
		Unified: "齿",
	},
	{
		VariantName: "CJK RADICAL J-SIMPLIFIED DRAGON",
		Variant: "⻯",
		Unified: "竜",
	},
	{
		VariantName: "CJK RADICAL C-SIMPLIFIED DRAGON",
		Variant: "⻰",
		Unified: "龙",
	},
	{
		VariantName: "CJK RADICAL TURTLE",
		Variant: "⻱",
		Unified: "龜",
	},
	{
		VariantName: "CJK RADICAL J-SIMPLIFIED TURTLE",
		Variant: "⻲",
		Unified: "亀",
	},
	{
		VariantName: "CJK RADICAL C-SIMPLIFIED TURTLE",
		Variant: "⻳",
		Unified: "龟",
	},
	{
		VariantName: "KANGXI RADICAL ONE",
		Variant: "⼀",
		Unified: "一",
	},
	{
		VariantName: "KANGXI RADICAL LINE",
		Variant: "⼁",
		Unified: "丨",
	},
	{
		VariantName: "KANGXI RADICAL DOT",
		Variant: "⼂",
		Unified: "丶",
	},
	{
		VariantName: "KANGXI RADICAL SLASH",
		Variant: "⼃",
		Unified: "丿",
	},
	{
		VariantName: "KANGXI RADICAL SECOND",
		Variant: "⼄",
		Unified: "乙",
	},
	{
		VariantName: "KANGXI RADICAL HOOK",
		Variant: "⼅",
		Unified: "亅",
	},
	{
		VariantName: "KANGXI RADICAL TWO",
		Variant: "⼆",
		Unified: "二",
	},
	{
		VariantName: "KANGXI RADICAL LID",
		Variant: "⼇",
		Unified: "亠",
	},
	{
		VariantName: "KANGXI RADICAL MAN",
		Variant: "⼈",
		Unified: "人",
	},
	{
		VariantName: "KANGXI RADICAL LEGS",
		Variant: "⼉",
		Unified: "儿",
	},
	{
		VariantName: "KANGXI RADICAL ENTER",
		Variant: "⼊",
		Unified: "入",
	},
	{
		VariantName: "KANGXI RADICAL EIGHT",
		Variant: "⼋",
		Unified: "八",
	},
	{
		VariantName: "KANGXI RADICAL DOWN BOX",
		Variant: "⼌",
		Unified: "冂",
	},
	{
		VariantName: "KANGXI RADICAL COVER",
		Variant: "⼍",
		Unified: "冖",
	},
	{
		VariantName: "KANGXI RADICAL ICE",
		Variant: "⼎",
		Unified: "冫",
	},
	{
		VariantName: "KANGXI RADICAL TABLE",
		Variant: "⼏",
		Unified: "几",
	},
	{
		VariantName: "KANGXI RADICAL OPEN BOX",
		Variant: "⼐",
		Unified: "凵",
	},
	{
		VariantName: "KANGXI RADICAL KNIFE",
		Variant: "⼑",
		Unified: "刀",
	},
	{
		VariantName: "KANGXI RADICAL POWER",
		Variant: "⼒",
		Unified: "力",
	},
	{
		VariantName: "KANGXI RADICAL WRAP",
		Variant: "⼓",
		Unified: "勹",
	},
	{
		VariantName: "KANGXI RADICAL SPOON",
		Variant: "⼔",
		Unified: "匕",
	},
	{
		VariantName: "KANGXI RADICAL RIGHT OPEN BOX",
		Variant: "⼕",
		Unified: "匚",
	},
	{
		VariantName: "KANGXI RADICAL HIDING ENCLOSURE",
		Variant: "⼖",
		Unified: "匸",
	},
	{
		VariantName: "KANGXI RADICAL TEN",
		Variant: "⼗",
		Unified: "十",
	},
	{
		VariantName: "KANGXI RADICAL DIVINATION",
		Variant: "⼘",
		Unified: "卜",
	},
	{
		VariantName: "KANGXI RADICAL SEAL",
		Variant: "⼙",
		Unified: "卩",
	},
	{
		VariantName: "KANGXI RADICAL CLIFF",
		Variant: "⼚",
		Unified: "厂",
	},
	{
		VariantName: "KANGXI RADICAL PRIVATE",
		Variant: "⼛",
		Unified: "厶",
	},
	{
		VariantName: "KANGXI RADICAL AGAIN",
		Variant: "⼜",
		Unified: "又",
	},
	{
		VariantName: "KANGXI RADICAL MOUTH",
		Variant: "⼝",
		Unified: "口",
	},
	{
		VariantName: "KANGXI RADICAL ENCLOSURE",
		Variant: "⼞",
		Unified: "囗",
	},
	{
		VariantName: "KANGXI RADICAL EARTH",
		Variant: "⼟",
		Unified: "土",
	},
	{
		VariantName: "KANGXI RADICAL SCHOLAR",
		Variant: "⼠",
		Unified: "士",
	},
	{
		VariantName: "KANGXI RADICAL GO",
		Variant: "⼡",
		Unified: "夂",
	},
	{
		VariantName: "KANGXI RADICAL GO SLOWLY",
		Variant: "⼢",
		Unified: "夊",
	},
	{
		VariantName: "KANGXI RADICAL EVENING",
		Variant: "⼣",
		Unified: "夕",
	},
	{
		VariantName: "KANGXI RADICAL BIG",
		Variant: "⼤",
		Unified: "大",
	},
	{
		VariantName: "KANGXI RADICAL WOMAN",
		Variant: "⼥",
		Unified: "女",
	},
	{
		VariantName: "KANGXI RADICAL CHILD",
		Variant: "⼦",
		Unified: "子",
	},
	{
		VariantName: "KANGXI RADICAL ROOF",
		Variant: "⼧",
		Unified: "宀",
	},
	{
		VariantName: "KANGXI RADICAL INCH",
		Variant: "⼨",
		Unified: "寸",
	},
	{
		VariantName: "KANGXI RADICAL SMALL",
		Variant: "⼩",
		Unified: "小",
	},
	{
		VariantName: "KANGXI RADICAL LAME",
		Variant: "⼪",
		Unified: "尢",
	},
	{
		VariantName: "KANGXI RADICAL CORPSE",
		Variant: "⼫",
		Unified: "尸",
	},
	{
		VariantName: "KANGXI RADICAL SPROUT",
		Variant: "⼬",
		Unified: "屮",
	},
	{
		VariantName: "KANGXI RADICAL MOUNTAIN",
		Variant: "⼭",
		Unified: "山",
	},
	{
		VariantName: "KANGXI RADICAL RIVER",
		Variant: "⼮",
		Unified: "巛",
	},
	{
		VariantName: "KANGXI RADICAL WORK",
		Variant: "⼯",
		Unified: "工",
	},
	{
		VariantName: "KANGXI RADICAL ONESELF",
		Variant: "⼰",
		Unified: "己",
	},
	{
		VariantName: "KANGXI RADICAL TURBAN",
		Variant: "⼱",
		Unified: "巾",
	},
	{
		VariantName: "KANGXI RADICAL DRY",
		Variant: "⼲",
		Unified: "干",
	},
	{
		VariantName: "KANGXI RADICAL SHORT THREAD",
		Variant: "⼳",
		Unified: "幺",
	},
	{
		VariantName: "KANGXI RADICAL DOTTED CLIFF",
		Variant: "⼴",
		Unified: "广",
	},
	{
		VariantName: "KANGXI RADICAL LONG STRIDE",
		Variant: "⼵",
		Unified: "廴",
	},
	{
		VariantName: "KANGXI RADICAL TWO HANDS",
		Variant: "⼶",
		Unified: "廾",
	},
	{
		VariantName: "KANGXI RADICAL SHOOT",
		Variant: "⼷",
		Unified: "弋",
	},
	{
		VariantName: "KANGXI RADICAL BOW",
		Variant: "⼸",
		Unified: "弓",
	},
	{
		VariantName: "KANGXI RADICAL SNOUT",
		Variant: "⼹",
		Unified: "彐",
	},
	{
		VariantName: "KANGXI RADICAL BRISTLE",
		Variant: "⼺",
		Unified: "彡",
	},
	{
		VariantName: "KANGXI RADICAL STEP",
		Variant: "⼻",
		Unified: "彳",
	},
	{
		VariantName: "KANGXI RADICAL HEART",
		Variant: "⼼",
		Unified: "心",
	},
	{
		VariantName: "KANGXI RADICAL HALBERD",
		Variant: "⼽",
		Unified: "戈",
	},
	{
		VariantName: "KANGXI RADICAL DOOR",
		Variant: "⼾",
		Unified: "戶",
	},
	{
		VariantName: "KANGXI RADICAL HAND",
		Variant: "⼿",
		Unified: "手",
	},
	{
		VariantName: "KANGXI RADICAL BRANCH",
		Variant: "⽀",
		Unified: "支",
	},
	{
		VariantName: "KANGXI RADICAL RAP",
		Variant: "⽁",
		Unified: "攴",
	},
	{
		VariantName: "KANGXI RADICAL SCRIPT",
		Variant: "⽂",
		Unified: "文",
	},
	{
		VariantName: "KANGXI RADICAL DIPPER",
		Variant: "⽃",
		Unified: "斗",
	},
	{
		VariantName: "KANGXI RADICAL AXE",
		Variant: "⽄",
		Unified: "斤",
	},
	{
		VariantName: "KANGXI RADICAL SQUARE",
		Variant: "⽅",
		Unified: "方",
	},
	{
		VariantName: "KANGXI RADICAL NOT",
		Variant: "⽆",
		Unified: "无",
	},
	{
		VariantName: "KANGXI RADICAL SUN",
		Variant: "⽇",
		Unified: "日",
	},
	{
		VariantName: "KANGXI RADICAL SAY",
		Variant: "⽈",
		Unified: "曰",
	},
	{
		VariantName: "KANGXI RADICAL MOON",
		Variant: "⽉",
		Unified: "月",
	},
	{
		VariantName: "KANGXI RADICAL TREE",
		Variant: "⽊",
		Unified: "木",
	},
	{
		VariantName: "KANGXI RADICAL LACK",
		Variant: "⽋",
		Unified: "欠",
	},
	{
		VariantName: "KANGXI RADICAL STOP",
		Variant: "⽌",
		Unified: "止",
	},
	{
		VariantName: "KANGXI RADICAL DEATH",
		Variant: "⽍",
		Unified: "歹",
	},
	{
		VariantName: "KANGXI RADICAL WEAPON",
		Variant: "⽎",
		Unified: "殳",
	},
	{
		VariantName: "KANGXI RADICAL DO NOT",
		Variant: "⽏",
		Unified: "毋",
	},
	{
		VariantName: "KANGXI RADICAL COMPARE",
		Variant: "⽐",
		Unified: "比",
	},
	{
		VariantName: "KANGXI RADICAL FUR",
		Variant: "⽑",
		Unified: "毛",
	},
	{
		VariantName: "KANGXI RADICAL CLAN",
		Variant: "⽒",
		Unified: "氏",
	},
	{
		VariantName: "KANGXI RADICAL STEAM",
		Variant: "⽓",
		Unified: "气",
	},
	{
		VariantName: "KANGXI RADICAL WATER",
		Variant: "⽔",
		Unified: "水",
	},
	{
		VariantName: "KANGXI RADICAL FIRE",
		Variant: "⽕",
		Unified: "火",
	},
	{
		VariantName: "KANGXI RADICAL CLAW",
		Variant: "⽖",
		Unified: "爪",
	},
	{
		VariantName: "KANGXI RADICAL FATHER",
		Variant: "⽗",
		Unified: "父",
	},
	{
		VariantName: "KANGXI RADICAL DOUBLE X",
		Variant: "⽘",
		Unified: "爻",
	},
	{
		VariantName: "KANGXI RADICAL HALF TREE TRUNK",
		Variant: "⽙",
		Unified: "爿",
	},
	{
		VariantName: "KANGXI RADICAL SLICE",
		Variant: "⽚",
		Unified: "片",
	},
	{
		VariantName: "KANGXI RADICAL FANG",
		Variant: "⽛",
		Unified: "牙",
	},
	{
		VariantName: "KANGXI RADICAL COW",
		Variant: "⽜",
		Unified: "牛",
	},
	{
		VariantName: "KANGXI RADICAL DOG",
		Variant: "⽝",
		Unified: "犬",
	},
	{
		VariantName: "KANGXI RADICAL PROFOUND",
		Variant: "⽞",
		Unified: "玄",
	},
	{
		VariantName: "KANGXI RADICAL JADE",
		Variant: "⽟",
		Unified: "玉",
	},
	{
		VariantName: "KANGXI RADICAL MELON",
		Variant: "⽠",
		Unified: "瓜",
	},
	{
		VariantName: "KANGXI RADICAL TILE",
		Variant: "⽡",
		Unified: "瓦",
	},
	{
		VariantName: "KANGXI RADICAL SWEET",
		Variant: "⽢",
		Unified: "甘",
	},
	{
		VariantName: "KANGXI RADICAL LIFE",
		Variant: "⽣",
		Unified: "生",
	},
	{
		VariantName: "KANGXI RADICAL USE",
		Variant: "⽤",
		Unified: "用",
	},
	{
		VariantName: "KANGXI RADICAL FIELD",
		Variant: "⽥",
		Unified: "田",
	},
	{
		VariantName: "KANGXI RADICAL BOLT OF CLOTH",
		Variant: "⽦",
		Unified: "疋",
	},
	{
		VariantName: "KANGXI RADICAL SICKNESS",
		Variant: "⽧",
		Unified: "疒",
	},
	{
		VariantName: "KANGXI RADICAL DOTTED TENT",
		Variant: "⽨",
		Unified: "癶",
	},
	{
		VariantName: "KANGXI RADICAL WHITE",
		Variant: "⽩",
		Unified: "白",
	},
	{
		VariantName: "KANGXI RADICAL SKIN",
		Variant: "⽪",
		Unified: "皮",
	},
	{
		VariantName: "KANGXI RADICAL DISH",
		Variant: "⽫",
		Unified: "皿",
	},
	{
		VariantName: "KANGXI RADICAL EYE",
		Variant: "⽬",
		Unified: "目",
	},
	{
		VariantName: "KANGXI RADICAL SPEAR",
		Variant: "⽭",
		Unified: "矛",
	},
	{
		VariantName: "KANGXI RADICAL ARROW",
		Variant: "⽮",
		Unified: "矢",
	},
	{
		VariantName: "KANGXI RADICAL STONE",
		Variant: "⽯",
		Unified: "石",
	},
	{
		VariantName: "KANGXI RADICAL SPIRIT",
		Variant: "⽰",
		Unified: "示",
	},
	{
		VariantName: "KANGXI RADICAL TRACK",
		Variant: "⽱",
		Unified: "禸",
	},
	{
		VariantName: "KANGXI RADICAL GRAIN",
		Variant: "⽲",
		Unified: "禾",
	},
	{
		VariantName: "KANGXI RADICAL CAVE",
		Variant: "⽳",
		Unified: "穴",
	},
	{
		VariantName: "KANGXI RADICAL STAND",
		Variant: "⽴",
		Unified: "立",
	},
	{
		VariantName: "KANGXI RADICAL BAMBOO",
		Variant: "⽵",
		Unified: "竹",
	},
	{
		VariantName: "KANGXI RADICAL RICE",
		Variant: "⽶",
		Unified: "米",
	},
	{
		VariantName: "KANGXI RADICAL SILK",
		Variant: "⽷",
		Unified: "糸",
	},
	{
		VariantName: "KANGXI RADICAL JAR",
		Variant: "⽸",
		Unified: "缶",
	},
	{
		VariantName: "KANGXI RADICAL NET",
		Variant: "⽹",
		Unified: "网",
	},
	{
		VariantName: "KANGXI RADICAL SHEEP",
		Variant: "⽺",
		Unified: "羊",
	},
	{
		VariantName: "KANGXI RADICAL FEATHER",
		Variant: "⽻",
		Unified: "羽",
	},
	{
		VariantName: "KANGXI RADICAL OLD",
		Variant: "⽼",
		Unified: "老",
	},
	{
		VariantName: "KANGXI RADICAL AND",
		Variant: "⽽",
		Unified: "而",
	},
	{
		VariantName: "KANGXI RADICAL PLOW",
		Variant: "⽾",
		Unified: "耒",
	},
	{
		VariantName: "KANGXI RADICAL EAR",
		Variant: "⽿",
		Unified: "耳",
	},
	{
		VariantName: "KANGXI RADICAL BRUSH",
		Variant: "⾀",
		Unified: "聿",
	},
	{
		VariantName: "KANGXI RADICAL MEAT",
		Variant: "⾁",
		Unified: "肉",
	},
	{
		VariantName: "KANGXI RADICAL MINISTER",
		Variant: "⾂",
		Unified: "臣",
	},
	{
		VariantName: "KANGXI RADICAL SELF",
		Variant: "⾃",
		Unified: "自",
	},
	{
		VariantName: "KANGXI RADICAL ARRIVE",
		Variant: "⾄",
		Unified: "至",
	},
	{
		VariantName: "KANGXI RADICAL MORTAR",
		Variant: "⾅",
		Unified: "臼",
	},
	{
		VariantName: "KANGXI RADICAL TONGUE",
		Variant: "⾆",
		Unified: "舌",
	},
	{
		VariantName: "KANGXI RADICAL OPPOSE",
		Variant: "⾇",
		Unified: "舛",
	},
	{
		VariantName: "KANGXI RADICAL BOAT",
		Variant: "⾈",
		Unified: "舟",
	},
	{
		VariantName: "KANGXI RADICAL STOPPING",
		Variant: "⾉",
		Unified: "艮",
	},
	{
		VariantName: "KANGXI RADICAL COLOR",
		Variant: "⾊",
		Unified: "色",
	},
	{
		VariantName: "KANGXI RADICAL GRASS",
		Variant: "⾋",
		Unified: "艸",
	},
	{
		VariantName: "KANGXI RADICAL TIGER",
		Variant: "⾌",
		Unified: "虍",
	},
	{
		VariantName: "KANGXI RADICAL INSECT",
		Variant: "⾍",
		Unified: "虫",
	},
	{
		VariantName: "KANGXI RADICAL BLOOD",
		Variant: "⾎",
		Unified: "血",
	},
	{
		VariantName: "KANGXI RADICAL WALK ENCLOSURE",
		Variant: "⾏",
		Unified: "行",
	},
	{
		VariantName: "KANGXI RADICAL CLOTHES",
		Variant: "⾐",
		Unified: "衣",
	},
	{
		VariantName: "KANGXI RADICAL WEST",
		Variant: "⾑",
		Unified: "襾",
	},
	{
		VariantName: "KANGXI RADICAL SEE",
		Variant: "⾒",
		Unified: "見",
	},
	{
		VariantName: "KANGXI RADICAL HORN",
		Variant: "⾓",
		Unified: "角",
	},
	{
		VariantName: "KANGXI RADICAL SPEECH",
		Variant: "⾔",
		Unified: "言",
	},
	{
		VariantName: "KANGXI RADICAL VALLEY",
		Variant: "⾕",
		Unified: "谷",
	},
	{
		VariantName: "KANGXI RADICAL BEAN",
		Variant: "⾖",
		Unified: "豆",
	},
	{
		VariantName: "KANGXI RADICAL PIG",
		Variant: "⾗",
		Unified: "豕",
	},
	{
		VariantName: "KANGXI RADICAL BADGER",
		Variant: "⾘",
		Unified: "豸",
	},
	{
		VariantName: "KANGXI RADICAL SHELL",
		Variant: "⾙",
		Unified: "貝",
	},
	{
		VariantName: "KANGXI RADICAL RED",
		Variant: "⾚",
		Unified: "赤",
	},
	{
		VariantName: "KANGXI RADICAL RUN",
		Variant: "⾛",
		Unified: "走",
	},
	{
		VariantName: "KANGXI RADICAL FOOT",
		Variant: "⾜",
		Unified: "足",
	},
	{
		VariantName: "KANGXI RADICAL BODY",
		Variant: "⾝",
		Unified: "身",
	},
	{
		VariantName: "KANGXI RADICAL CART",
		Variant: "⾞",
		Unified: "車",
	},
	{
		VariantName: "KANGXI RADICAL BITTER",
		Variant: "⾟",
		Unified: "辛",
	},
	{
		VariantName: "KANGXI RADICAL MORNING",
		Variant: "⾠",
		Unified: "辰",
	},
	{
		VariantName: "KANGXI RADICAL WALK",
		Variant: "⾡",
		Unified: "辵",
	},
	{
		VariantName: "KANGXI RADICAL CITY",
		Variant: "⾢",
		Unified: "邑",
	},
	{
		VariantName: "KANGXI RADICAL WINE",
		Variant: "⾣",
		Unified: "酉",
	},
	{
		VariantName: "KANGXI RADICAL DISTINGUISH",
		Variant: "⾤",
		Unified: "釆",
	},
	{
		VariantName: "KANGXI RADICAL VILLAGE",
		Variant: "⾥",
		Unified: "里",
	},
	{
		VariantName: "KANGXI RADICAL GOLD",
		Variant: "⾦",
		Unified: "金",
	},
	{
		VariantName: "KANGXI RADICAL LONG",
		Variant: "⾧",
		Unified: "長",
	},
	{
		VariantName: "KANGXI RADICAL GATE",
		Variant: "⾨",
		Unified: "門",
	},
	{
		VariantName: "KANGXI RADICAL MOUND",
		Variant: "⾩",
		Unified: "阜",
	},
	{
		VariantName: "KANGXI RADICAL SLAVE",
		Variant: "⾪",
		Unified: "隶",
	},
	{
		VariantName: "KANGXI RADICAL SHORT TAILED BIRD",
		Variant: "⾫",
		Unified: "隹",
	},
	{
		VariantName: "KANGXI RADICAL RAIN",
		Variant: "⾬",
		Unified: "雨",
	},
	{
		VariantName: "KANGXI RADICAL BLUE",
		Variant: "⾭",
		Unified: "靑",
	},
	{
		VariantName: "KANGXI RADICAL WRONG",
		Variant: "⾮",
		Unified: "非",
	},
	{
		VariantName: "KANGXI RADICAL FACE",
		Variant: "⾯",
		Unified: "面",
	},
	{
		VariantName: "KANGXI RADICAL LEATHER",
		Variant: "⾰",
		Unified: "革",
	},
	{
		VariantName: "KANGXI RADICAL TANNED LEATHER",
		Variant: "⾱",
		Unified: "韋",
	},
	{
		VariantName: "KANGXI RADICAL LEEK",
		Variant: "⾲",
		Unified: "韭",
	},
	{
		VariantName: "KANGXI RADICAL SOUND",
		Variant: "⾳",
		Unified: "音",
	},
	{
		VariantName: "KANGXI RADICAL LEAF",
		Variant: "⾴",
		Unified: "頁",
	},
	{
		VariantName: "KANGXI RADICAL WIND",
		Variant: "⾵",
		Unified: "風",
	},
	{
		VariantName: "KANGXI RADICAL FLY",
		Variant: "⾶",
		Unified: "飛",
	},
	{
		VariantName: "KANGXI RADICAL EAT",
		Variant: "⾷",
		Unified: "食",
	},
	{
		VariantName: "KANGXI RADICAL HEAD",
		Variant: "⾸",
		Unified: "首",
	},
	{
		VariantName: "KANGXI RADICAL FRAGRANT",
		Variant: "⾹",
		Unified: "香",
	},
	{
		VariantName: "KANGXI RADICAL HORSE",
		Variant: "⾺",
		Unified: "馬",
	},
	{
		VariantName: "KANGXI RADICAL BONE",
		Variant: "⾻",
		Unified: "骨",
	},
	{
		VariantName: "KANGXI RADICAL TALL",
		Variant: "⾼",
		Unified: "高",
	},
	{
		VariantName: "KANGXI RADICAL HAIR",
		Variant: "⾽",
		Unified: "髟",
	},
	{
		VariantName: "KANGXI RADICAL FIGHT",
		Variant: "⾾",
		Unified: "鬥",
	},
	{
		VariantName: "KANGXI RADICAL SACRIFICIAL WINE",
		Variant: "⾿",
		Unified: "鬯",
	},
	{
		VariantName: "KANGXI RADICAL CAULDRON",
		Variant: "⿀",
		Unified: "鬲",
	},
	{
		VariantName: "KANGXI RADICAL GHOST",
		Variant: "⿁",
		Unified: "鬼",
	},
	{
		VariantName: "KANGXI RADICAL FISH",
		Variant: "⿂",
		Unified: "魚",
	},
	{
		VariantName: "KANGXI RADICAL BIRD",
		Variant: "⿃",
		Unified: "鳥",
	},
	{
		VariantName: "KANGXI RADICAL SALT",
		Variant: "⿄",
		Unified: "鹵",
	},
	{
		VariantName: "KANGXI RADICAL DEER",
		Variant: "⿅",
		Unified: "鹿",
	},
	{
		VariantName: "KANGXI RADICAL WHEAT",
		Variant: "⿆",
		Unified: "麥",
	},
	{
		VariantName: "KANGXI RADICAL HEMP",
		Variant: "⿇",
		Unified: "麻",
	},
	{
		VariantName: "KANGXI RADICAL YELLOW",
		Variant: "⿈",
		Unified: "黃",
	},
	{
		VariantName: "KANGXI RADICAL MILLET",
		Variant: "⿉",
		Unified: "黍",
	},
	{
		VariantName: "KANGXI RADICAL BLACK",
		Variant: "⿊",
		Unified: "黑",
	},
	{
		VariantName: "KANGXI RADICAL EMBROIDERY",
		Variant: "⿋",
		Unified: "黹",
	},
	{
		VariantName: "KANGXI RADICAL FROG",
		Variant: "⿌",
		Unified: "黽",
	},
	{
		VariantName: "KANGXI RADICAL TRIPOD",
		Variant: "⿍",
		Unified: "鼎",
	},
	{
		VariantName: "KANGXI RADICAL DRUM",
		Variant: "⿎",
		Unified: "鼓",
	},
	{
		VariantName: "KANGXI RADICAL RAT",
		Variant: "⿏",
		Unified: "鼠",
	},
	{
		VariantName: "KANGXI RADICAL NOSE",
		Variant: "⿐",
		Unified: "鼻",
	},
	{
		VariantName: "KANGXI RADICAL EVEN",
		Variant: "⿑",
		Unified: "齊",
	},
	{
		VariantName: "KANGXI RADICAL TOOTH",
		Variant: "⿒",
		Unified: "齒",
	},
	{
		VariantName: "KANGXI RADICAL DRAGON",
		Variant: "⿓",
		Unified: "龍",
	},
	{
		VariantName: "KANGXI RADICAL TURTLE",
		Variant: "⿔",
		Unified: "龜",
	},
	{
		VariantName: "KANGXI RADICAL FLUTE",
		Variant: "⿕",
		Unified: "龠",
	},
	{
		VariantName: "CJK STROKE HZG",
		Variant: "㇆",
		Unified: "𠃌",
	},
	{
		VariantName: "CJK STROKE N",
		Variant: "㇏",
		Unified: "乀",
	},
	{
		VariantName: "CJK STROKE H",
		Variant: "㇐",
		Unified: "一",
	},
	{
		VariantName: "CJK STROKE S",
		Variant: "㇑",
		Unified: "丨",
	},
	{
		VariantName: "[2] CJK STROKE P..CJK STROKE SP",
		Variant: "㇒",
		Unified: "丿",
	},
	{
		VariantName: "[2] CJK STROKE P..CJK STROKE SP",
		Variant: "㇓",
		Unified: "丿",
	},
	{
		VariantName: "CJK STROKE D",
		Variant: "㇔",
		Unified: "丶",
	},
	{
		VariantName: "CJK STROKE HZ",
		Variant: "㇕",
		Unified: "𠃍",
	},
	{
		VariantName: "CJK STROKE HG",
		Variant: "㇖",
		Unified: "乛",
	},
	{
		VariantName: "CJK STROKE SZ",
		Variant: "㇗",
		Unified: "𠃊",
	},
	{
		VariantName: "CJK STROKE SWZ",
		Variant: "㇘",
		Unified: "𠃎",
	},
	{
		VariantName: "CJK STROKE ST",
		Variant: "㇙",
		Unified: "𠄌",
	},
	{
		VariantName: "CJK STROKE SG",
		Variant: "㇚",
		Unified: "亅",
	},
	{
		VariantName: "CJK STROKE PD",
		Variant: "㇛",
		Unified: "𡿨",
	},
	{
		VariantName: "CJK STROKE PZ",
		Variant: "㇜",
		Unified: "𠃋",
	},
	{
		VariantName: "CJK STROKE TN",
		Variant: "㇝",
		Unified: "乀",
	},
	{
		VariantName: "CJK STROKE SZZ",
		Variant: "㇞",
		Unified: "𠃑",
	},
	{
		VariantName: "CJK STROKE SWG",
		Variant: "㇟",
		Unified: "乚",
	},
	{
		VariantName: "CJK STROKE HXWG",
		Variant: "㇠",
		Unified: "乙",
	},
	{
		VariantName: "CJK STROKE HZZZG",
		Variant: "㇡",
		Unified: "𠄎",
	},
}

var MappedPairs = map[string]string{
	"⼯": "工",
	"⽈": "曰",
	"⽘": "爻",
	"⽮": "矢",
	"⿏": "鼠",
	"⻖": "阝",
	"⻡": "𩠐",
	"⾊": "色",
	"⺂": "乛",
	"⽅": "方",
	"⼗": "十",
	"⽩": "白",
	"⺟": "母",
	"⻘": "青",
	"⽐": "比",
	"㇛": "𡿨",
	"⼏": "几",
	"⾌": "虍",
	"⾶": "飛",
	"⺑": "𡯂",
	"⺲": "罒",
	"⻔": "门",
	"㇞": "𠃑",
	"⽾": "耒",
	"⾃": "自",
	"⼨": "寸",
	"⽤": "用",
	"⻨": "麦",
	"⾯": "面",
	"⿁": "鬼",
	"⿓": "龍",
	"⿔": "龜",
	"㇚": "亅",
	"⼓": "勹",
	"⼬": "屮",
	"⽯": "石",
	"⾞": "車",
	"⺨": "犭",
	"⼰": "己",
	"⼈": "人",
	"⼚": "厂",
	"⽝": "犬",
	"㇠": "乙",
	"⻗": "雨",
	"⻢": "马",
	"⾂": "臣",
	"⾆": "舌",
	"⻏": "邑",
	"⽀": "支",
	"⼄": "乙",
	"⺻": "聿",
	"⻣": "骨",
	"⾁": "肉",
	"⾠": "辰",
	"⾻": "骨",
	"⺦": "丬",
	"⼷": "弋",
	"⼢": "夊",
	"⼳": "幺",
	"⽏": "毋",
	"⽲": "禾",
	"⽻": "羽",
	"⺤": "爫",
	"⻊": "𧾷",
	"⼅": "亅",
	"⽷": "糸",
	"⿐": "鼻",
	"⺇": "𠘨",
	"⻁": "虎",
	"⽨": "癶",
	"⾥": "里",
	"⿊": "黑",
	"⻒": "镸",
	"⼖": "匸",
	"⼺": "彡",
	"⾓": "角",
	"㇔": "丶",
	"⻓": "长",
	"⼦": "子",
	"⻀": "艹",
	"⼸": "弓",
	"⾢": "邑",
	"⿎": "鼓",
	"⺆": "冂",
	"⺪": "𤴔",
	"⼫": "尸",
	"⽥": "田",
	"⾋": "艸",
	"⾧": "長",
	"⾱": "韋",
	"⻪": "黾",
	"⻱": "龜",
	"⼱": "巾",
	"⽍": "歹",
	"⾇": "舛",
	"⻂": "衤",
	"⻫": "斉",
	"⺭": "礻",
	"⻉": "贝",
	"⻟": "飠",
	"⼤": "大",
	"⾗": "豕",
	"⾲": "韭",
	"⺥": "爫",
	"⺫": "目",
	"⼊": "入",
	"⼐": "凵",
	"⽣": "生",
	"⽴": "立",
	"⾪": "隶",
	"⾾": "鬥",
	"⺖": "忄",
	"⺳": "㓁",
	"⼽": "戈",
	"⺾": "艹",
	"⼌": "冂",
	"⻑": "長",
	"⼾": "戶",
	"⽪": "皮",
	"⽰": "示",
	"⾫": "隹",
	"⿂": "魚",
	"⺣": "灬",
	"⻆": "角",
	"⼶": "廾",
	"⽹": "网",
	"⽼": "老",
	"⾮": "非",
	"⺘": "扌",
	"⻛": "风",
	"⾐": "衣",
	"⼴": "广",
	"⼻": "彳",
	"⺶": "羊",
	"⻲": "亀",
	"⼪": "尢",
	"⼵": "廴",
	"⽂": "文",
	"⽡": "瓦",
	"⺓": "幺",
	"⺜": "日",
	"⽶": "米",
	"⾀": "聿",
	"⻭": "歯",
	"⽖": "爪",
	"⽸": "缶",
	"⾒": "見",
	"⿀": "鬲",
	"㇒": "丿",
	"⺊": "卜",
	"⺎": "兀",
	"⻠": "饣",
	"⼇": "亠",
	"⾍": "虫",
	"⾰": "革",
	"⾿": "鬯",
	"⺡": "氵",
	"⻚": "页",
	"⺠": "民",
	"⼲": "干",
	"⼹": "彐",
	"⾙": "貝",
	"⾝": "身",
	"㇜": "𠃋",
	"⺄": "乙",
	"⺞": "歺",
	"⼟": "土",
	"⽓": "气",
	"⾡": "辵",
	"⾨": "門",
	"⾳": "音",
	"⺩": "王",
	"⺯": "糹",
	"⺵": "𦉫",
	"⻎": "辶",
	"⼎": "冫",
	"⽌": "止",
	"⽠": "瓜",
	"⾷": "食",
	"⺃": "乚",
	"⺛": "旡",
	"⼒": "力",
	"㇙": "𠄌",
	"⼼": "心",
	"⽱": "禸",
	"⾖": "豆",
	"⾭": "靑",
	"㇆": "𠃌",
	"㇖": "乛",
	"⻐": "钅",
	"⼠": "士",
	"⻤": "鬼",
	"⼡": "夂",
	"⽭": "矛",
	"⾏": "行",
	"⾘": "豸",
	"⾛": "走",
	"⺁": "厂",
	"⺋": "㔾",
	"㇑": "丨",
	"⽢": "甘",
	"⽳": "穴",
	"⾵": "風",
	"⺱": "罓",
	"⽑": "毛",
	"⾟": "辛",
	"㇝": "乀",
	"⻜": "飞",
	"⽁": "攴",
	"⾈": "舟",
	"⿈": "黃",
	"⺐": "尢",
	"⼣": "夕",
	"⻋": "车",
	"⼂": "丶",
	"⾼": "高",
	"⺗": "心",
	"⺿": "艹",
	"⼮": "巛",
	"⾩": "阜",
	"⻧": "卤",
	"⼜": "又",
	"⽕": "火",
	"⽉": "月",
	"⽋": "欠",
	"⺼": "肉",
	"⻍": "辶",
	"⻞": "𩙿",
	"⼭": "山",
	"⽔": "水",
	"⿄": "鹵",
	"⺏": "尣",
	"⺴": "冗",
	"⿉": "黍",
	"⻮": "齿",
	"⾚": "赤",
	"⺷": "𦍌",
	"⻃": "覀",
	"⼞": "囗",
	"⺽": "𦥑",
	"⻝": "食",
	"⼆": "二",
	"⽟": "玉",
	"⽬": "目",
	"⺈": "刀",
	"⺍": "小",
	"⻌": "辶",
	"⽒": "氏",
	"⾎": "血",
	"⾺": "馬",
	"⿑": "齊",
	"⺙": "攵",
	"⺮": "𥫗",
	"⿋": "黹",
	"㇕": "𠃍",
	"⼝": "口",
	"⽗": "父",
	"⼔": "匕",
	"⼿": "手",
	"⽇": "日",
	"⽞": "玄",
	"㇐": "一",
	"⺅": "亻",
	"⼋": "八",
	"⿆": "麥",
	"⿕": "龠",
	"⻩": "黄",
	"⿅": "鹿",
	"⿃": "鳥",
	"㇡": "𠄎",
	"⻙": "韦",
	"⾦": "金",
	"⽜": "牛",
	"⾉": "艮",
	"⺔": "彑",
	"⼁": "丨",
	"⻦": "鸟",
	"⻬": "齐",
	"⼥": "女",
	"⽄": "斤",
	"⽎": "殳",
	"⽽": "而",
	"⺕": "彐",
	"⻄": "西",
	"⾣": "酉",
	"⻕": "𨸏",
	"⼍": "冖",
	"⽃": "斗",
	"⿌": "黽",
	"⿍": "鼎",
	"⺝": "月",
	"⻇": "𧢲",
	"⻅": "见",
	"⿒": "齒",
	"㇟": "乚",
	"⺧": "牛",
	"⺬": "示",
	"⽛": "牙",
	"⽿": "耳",
	"⾽": "髟",
	"⺹": "耂",
	"⼃": "丿",
	"⻰": "龙",
	"⼕": "匚",
	"⼧": "宀",
	"⽦": "疋",
	"⾕": "谷",
	"⺒": "巳",
	"⺸": "𦍋",
	"⽆": "无",
	"⽫": "皿",
	"⾔": "言",
	"⻈": "讠",
	"⼉": "儿",
	"⾑": "襾",
	"⽚": "片",
	"⽧": "疒",
	"⽺": "羊",
	"⾬": "雨",
	"㇘": "𠃎",
	"⻥": "鱼",
	"⼑": "刀",
	"⼛": "厶",
	"⽊": "木",
	"⾤": "釆",
	"⾴": "頁",
	"⾸": "首",
	"⾹": "香",
	"⺰": "纟",
	"⺺": "肀",
	"⿇": "麻",
	"⼩": "小",
	"⾄": "至",
	"⾅": "臼",
	"⺢": "氺",
	"⼀": "一",
	"⼘": "卜",
	"⼙": "卩",
	"⽙": "爿",
	"⽵": "竹",
	"⾜": "足",
	"㇏": "乀",
	"⺌": "小",
	"⻯": "竜",
	"㇓": "丿",
	"㇗": "𠃊",
	"⺉": "刂",
	"⻳": "龟",
}